# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHEAP', 'Cheapest Flight'), ('NOLAY', 'No Layover')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_duration_min', models.IntegerField()),
                ('airline', models.CharField(max_length=50)),
                ('number_of_miles', models.IntegerField()),
                ('query_dateTime', models.DateField()),
                ('origin', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
                ('departing_date', models.DateField()),
                ('return_date', models.DateField()),
                ('departing_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('query_duration_sec', models.IntegerField()),
            ],
        ),
    ]
