# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20161231_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_info',
            name='legs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
