# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_flight_info_legs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_info',
            old_name='flight_duration_min',
            new_name='flight_duration_arrival_min',
        ),
        migrations.RenameField(
            model_name='flight_info',
            old_name='legs',
            new_name='flight_duration_departure_min',
        ),
        migrations.AddField(
            model_name='flight_info',
            name='legs_departure',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight_info',
            name='legs_return',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
