# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20170101_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_info',
            old_name='flight_duration_arrival_min',
            new_name='flight_duration_return_min',
        ),
    ]
